apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevin6191015/k8s.git
    targetRevision: main
    path: overlays/dev           # 指向 dev 的 kustomize 目錄
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true                # 自動清理 Git 移除的資源
      selfHeal: true             # 偵測偏離自我修復
    syncOptions:
      - CreateNamespace=true     # 目標 namespace 不存在就建立
