apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../../base/backend

images:
  - name: selab-backend            # ← 必須對應 base/backend.yaml 內的占位 image 名稱
    newName: ghcr.io/kevin6191015/new_app-backend   # ← 你的 GHCR 映像路徑
    newTag: "latest"                                # ← 手動 Sync 時拉最新版

replicas:
  - name: spring-backend

    count: 1
