apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../../base/frontend

images:
  - name: selab-frontend          # ← 必須對應 base/frontend.yaml 內的占位 image 名稱
    newName: ghcr.io/kevin6191015/new_app-frontend   # ← 你的 GHCR 映像路徑
    newTag: "latest"          
