apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../../base/frontend

images:
  - name: selab-frontend          # ← 必須對應 base/frontend.yaml 內的占位 image 名稱
    newName: kevin0413/selab-frontend
    newTag: "1.0.0"
