apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: "kevin"
  DB_PASSWORD: "secret"
  APP_JWT_SECRET: "please-change-to-a-very-long-random-secret-string-at-least-64-bytes----------------------------------"
